import os
import shutil
import string
import platform

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import flopy
import pyemu

abet = string.ascii_uppercase

unit_dict = {"head":"sw-gw flux $\\frac{ft^3}{d}$",
                "tail": "sw-gw flux $\\frac{ft^3}{d}$",
                "trgw" : "gw level $ft$",
                "gage" : "sw flux $\\frac{ft^3}{d}$"}
label_dict = {"head": "headwater",
             "tail": "tailwater",
             "trgw_2_2_9": "gw_1",
              "trgw_2_33_7": "gw_2",
              "trgw_0_9_1" : "gw_3",
             "gage": "sw_1"}

def prep_mf6_model(org_ws):
    
    #if not os.path.exists(os.path.join(org_ws,"freyberg6.nam")):
    if True:
        #first mod the nam file and the dumbass last reach bottom - sigh
        m = flopy.modflow.Modflow.load("freyberg.nam",model_ws=org_ws,check=False)
        print(m.sfr.reach_data.dtype)
        last_reach_bot = m.sfr.reach_data["strtop"][-1] - m.sfr.reach_data["strthick"][-1]
        cell_bot = m.dis.botm[0].array[m.sfr.reach_data["i"][-1],m.sfr.reach_data["j"][-1]]
        print(cell_bot,last_reach_bot)
        if last_reach_bot <= cell_bot:
            m.sfr.reach_data["strtop"][-1] += 0.001
        #m.wel.stress_period_data[7]["flux"] = m.wel.stress_period_data[8]["flux"] * 1.01
        for kper in range(1,m.nper):
            m.wel.stress_period_data[kper]["flux"] = m.wel.stress_period_data[0]["flux"] * (1+ (np.random.random() * 0.001))
            m.rch.rech[kper] = m.rch.rech[0].array * (1 + (np.random.random() * 0.001))

        m.external_path = "."

        m.write_input()
        lines = open(os.path.join(org_ws,"freyberg.nam"),'r').readlines()
        with open(os.path.join(org_ws,"freyberg_mod.nam"),'w') as f:
            for line in lines:
                if ".sfr.out" in line and not "REPLACE" in line:
                    line = line.strip() + " REPLACE\n"
                f.write(line)
        pyemu.os_utils.run("mf5to6 freyberg_mod.nam freyberg6",cwd=org_ws)


    new_ws = org_ws + "_test"
    if os.path.exists(new_ws):
        shutil.rmtree(new_ws)
    os.mkdir(new_ws)
    sim = flopy.mf6.MFSimulation.load(sim_ws=org_ws)
    sim.simulation_data.mfpath.set_sim_path(new_ws)
    sim.set_all_data_external()

    sim.name_file.continue_ = True
    m = sim.get_model("freyberg6")

    redis_fac = m.dis.nrow.data / 40 #in case this is a finely discret version

    obs_df = pd.read_csv("obs_loc.csv")
    obs_df.loc[:,"row"] = (obs_df.row * redis_fac).apply(np.int)
    obs_df.loc[:, "col"] = (obs_df.col * redis_fac).apply(np.int)


    obs_df.loc[:,"layer"] = 3
    obs_df.loc[:,"name"] = obs_df.apply(lambda x: "trgw_{0}_{1}_{2}".\
        format(x.layer-1,x.row-1,x.col-1),axis=1)
    obs_df.loc[:,"obstype"] = "HEAD"
    obs_df.loc[:,"col"] = obs_df.col.apply(np.int)
    obs_df2 = obs_df.copy()
    obs_df2.loc[:,"layer"] = 1
    obs_df2.loc[:,"name"] = obs_df2.apply(lambda x: "trgw_{0}_{1}_{2}".\
        format(x.layer-1,x.row-1,x.col-1),axis=1)

    obs_df = pd.concat([obs_df, obs_df2])
    obs_df['idxs'] = list(zip(obs_df.layer - 1, obs_df.row - 1, obs_df.col - 1))
    obs = flopy.mf6.ModflowUtlobs(
        m, pname='head_obs', digits=10, print_input=True,
        continuous={
            'heads.csv':
                obs_df.loc[:, ["name", "obstype", "idxs"]].to_records(
                    index=False)})


    m.sfr.boundnames = True
    m.sfr.obs.initialize(continuous={
        'sfr.csv': [('headwater', 'SFR', 'headwater'),
                    ('tailwater', 'SFR', 'tailwater'),
                    ('gage_1', 'inflow', 40*redis_fac)]}, filename='sfr.obs')
    pkd = m.sfr.packagedata.array.copy()
    pkd['boundname'] = 'headwater'
    pkd['boundname'][pkd.rno > int(m.dis.nrow.data / 2)] = 'tailwater'
    m.sfr.packagedata = pkd

    sim.set_all_data_external()
    sim.write_simulation()
    #shutil.copy2(os.path.join(org_ws,"mf6.exe"),os.path.join(new_ws,"mf6.exe"))
    pyemu.os_utils.run("mf6",cwd=new_ws)
    #ext_dict = {""}


def setup_interface(org_ws,num_reals=100):
    
    sim = flopy.mf6.MFSimulation.load(sim_ws=org_ws)
    m = sim.get_model("freyberg6")
    redis_fac = m.dis.nrow.data / 40
    template_ws = org_ws.split('_')[1] + "_template"
    
    sr = m.modelgrid
    # set up PstFrom object
    pf = pyemu.prototypes.PstFrom(original_d=org_ws, new_d=template_ws,
                 remove_existing=True,
                 longnames=True, spatial_reference=sr,
                 zero_based=False,start_datetime="1-1-2018")
    # obs
    #   using tabular style model output
    #   (generated by pyemu.gw_utils.setup_hds_obs())
    # pf.add_observations('freyberg.hds.dat', insfile='freyberg.hds.dat.ins2',
    #                     index_cols='obsnme', use_cols='obsval', prefix='hds')

    df = pd.read_csv(os.path.join(org_ws, "sfr.csv"), index_col=0)
    pf.add_observations("sfr.csv", insfile="sfr.csv.ins", index_cols="time", use_cols=list(df.columns.values),
                        prefix="sfr")

    df = pd.read_csv(os.path.join(org_ws, "heads.csv"), index_col=0)
    pf.add_observations("heads.csv", insfile="heads.csv.ins", index_cols="time", use_cols=list(df.columns.values),
                        prefix="hds")

    # probs want to setup several different variograms for each prop?
    grid_v = pyemu.geostats.ExpVario(contribution=1.0,a=500)
    grid_gs = pyemu.geostats.GeoStruct(variograms=grid_v)
    pp_v = pyemu.geostats.ExpVario(contribution=1.0, a=2000)
    pp_gs = pyemu.geostats.GeoStruct(variograms=pp_v)
    rch_v = pyemu.geostats.ExpVario(contribution=1.0, a=1000)
    rch_gs = pyemu.geostats.GeoStruct(variograms=rch_v)
    rch_temporal_gs = pyemu.geostats.GeoStruct(variograms=pyemu.geostats.ExpVario(contribution=1.0,a=60))
    pf.extra_py_imports.append('flopy')
    ib = m.dis.idomain[0].array
    tags = {"npf_k_":[0.1,10.],"npf_k33_":[.1,10],"sto_ss":[.1,10],"sto_sy":[.9,1.1],"rch_recharge":[.5,1.5]}
    dts = pd.to_datetime("1-1-2018") + pd.to_timedelta(np.cumsum(sim.tdis.perioddata.array["perlen"]),unit="d")

    for tag,bnd in tags.items():
        lb,ub = bnd[0],bnd[1]
        arr_files = [f for f in os.listdir(template_ws) if tag in f and f.endswith(".txt")]

        if len(arr_files) == 0:
            print("warning: no array files found for ",tag)
            continue
        for arr_file in arr_files:
            arr = np.loadtxt(os.path.join(template_ws,arr_file)).reshape(ib.shape)
            np.savetxt(os.path.join(template_ws,arr_file),arr,fmt="%15.6E")
        if "rch" in tag:
            pf.add_parameters(filenames=arr_files, par_type="grid", par_name_base="rch_gr",
                              pargp="rch_gr", zone_array=ib, upper_bound=ub, lower_bound=lb,
                              geostruct=rch_gs)
            for arr_file in arr_files:
                kper = int(arr_file.split('.')[1].split('_')[-1]) - 1
                pf.add_parameters(filenames=arr_file,par_type="constant",par_name_base=arr_file.split('.')[1]+"_cn",
                                  pargp="rch_const",zone_array=ib,upper_bound=ub,lower_bound=lb,geostruct=rch_temporal_gs,
                                  datetime=dts[kper])
        else:
            for arr_file in arr_files:
                pf.add_parameters(filenames=arr_file,par_type="grid",par_name_base=arr_file.split('.')[1]+"_gr",
                                  pargp=arr_file.split('.')[1]+"_gr",zone_array=ib,upper_bound=ub,lower_bound=lb,
                                  geostruct=grid_gs)
                pf.add_parameters(filenames=arr_file, par_type="pilotpoints", par_name_base=arr_file.split('.')[1]+"_pp",
                                  pargp=arr_file.split('.')[1]+"_pp", zone_array=ib,upper_bound=ub,lower_bound=lb,
                                  pp_space=int(5 * redis_fac),geostruct=pp_gs)

    
    list_files = [f for f in os.listdir(org_ws) if "freyberg6.wel_stress_period_data_" in f and f.endswith(".txt")]
    for list_file in list_files:
        kper = int(list_file.split(".")[1].split('_')[-1]) - 1
        # add spatially constant, but temporally correlated wel flux pars
        pf.add_parameters(filenames=list_file,par_type="constant",par_name_base="twel_mlt_{0}".format(kper),
                          pargp="twel_mlt".format(kper),index_cols=[0,1,2],use_cols=[3],
                          upper_bound=1.5,lower_bound=0.5, datetime=dts[kper], geostruct=rch_temporal_gs)

        # add temporally indep, but spatially correlated wel flux pars
        pf.add_parameters(filenames=list_file, par_type="grid", par_name_base="wel_grid_{0}".format(kper),
                          pargp="wel_{0}".format(kper), index_cols=[0, 1, 2], use_cols=[3],
                          upper_bound=1.5, lower_bound=0.5)

    # test non spatial idx in list like
    pf.add_parameters(filenames="freyberg6.sfr_packagedata.txt", par_name_base="sfr_rhk",
                      pargp="sfr_rhk", index_cols=[0,1,2,3], use_cols=[9], upper_bound=10.,
                      lower_bound=0.1,
                      par_type="grid")

    # add model run command
    pf.mod_sys_cmds.append("mf6")
    print(pf.mult_files)
    print(pf.org_files)

    # build pest
    pst = pf.build_pst('freyberg.pst')

    pe = pf.draw(num_reals, use_specsim=True)
    pe.to_binary(os.path.join(template_ws, "prior.jcb"))

    pst.control_data.noptmax = 0
    pst.pestpp_options["additional_ins_delimiters"] = ","

    pst.write(os.path.join(pf.new_d, "freyberg.pst"))
    pyemu.os_utils.run("{0} freyberg.pst".format(
        os.path.join("pestpp-ies")), cwd=pf.new_d)

    res_file = os.path.join(pf.new_d, "freyberg.base.rei")
    assert os.path.exists(res_file), res_file
    pst.set_res(res_file)
    print(pst.phi)

    pst.control_data.noptmax = -1
    pst.pestpp_options["ies_par_en"] = "prior.jcb"
    pst.write(os.path.join(pf.new_d, "freyberg.pst"))

    #assert pst.phi < 1.0e-5, pst.phi


def run_prior_mc(t_d):
    pyemu.os_utils.start_workers(t_d,"pestpp-ies","freyberg.pst",num_workers=5,worker_root=".",
                                 master_dir=t_d.replace("template","master"))

def make_kickass_figs():
    m_d_c = "monthly_master"
    m_d_f = "daily_master"

    sim = flopy.mf6.MFSimulation.load(sim_ws=m_d_f)
    m = sim.get_model("freyberg6")
    redis_fac = m.dis.nrow.data / 40

    pst_c = pyemu.Pst(os.path.join(m_d_c,"freyberg.pst"))
    pst_f = pyemu.Pst(os.path.join(m_d_f, "freyberg.pst"))

    oe_c = pd.read_csv(os.path.join(m_d_c,"freyberg.0.obs.csv"),index_col=0)
    oe_f = pd.read_csv(os.path.join(m_d_f,"freyberg.0.obs.csv"),index_col=0)

    obs_c = pst_c.observation_data
    hds_c = obs_c.loc[obs_c.obsnme.apply(lambda x: x.startswith("hds")),:].copy()
    hds_c.loc[:, "k"] = hds_c.obsnme.apply(lambda x: int(x.split('_')[2]))
    hds_c.loc[:, "time"] = hds_c.obsnme.apply(lambda x: float(x.split('_')[-1].split(':')[1]))

    #hds_c = hds_c.loc[hds_c.k == 2]

    obs_f = pst_f.observation_data
    hds_f = obs_f.loc[obs_f.obsnme.apply(lambda x: x.startswith("hds")), :].copy()
    hds_f.loc[:, "k"] = hds_f.obsnme.apply(lambda x: int(x.split('_')[2]))
    #hds_f = hds_f.loc[hds_f.k == 2]
    hds_f.loc[:,"i"] = hds_f.obsnme.apply(lambda x: int(x.split('_')[3]))
    hds_f.loc[:, "j"] = hds_f.obsnme.apply(lambda x: int(x.split('_')[4]))
    hds_f.loc[:, "time"] = hds_f.obsnme.apply(lambda x: float(x.split('_')[-1].split(':')[1]))

    hds_f.loc[:,"org_i"] = (hds_f.i / redis_fac).apply(np.int)
    hds_f.loc[:, "org_j"] = (hds_f.j / redis_fac).apply(np.int)
    hds_f.loc[:,"org_obgnme"] = hds_f.apply(lambda x: "hds_usecol:trgw_{0}_{1}_{2}".format(x.k,x.org_i,x.org_j),axis=1)

    gage_c = obs_c.loc[obs_c.obsnme.apply(lambda x: "gage" in x),:].copy()
    gage_c.loc[:,"time"] = gage_c.obsnme.apply(lambda x: float(x.split(':')[-1]))
    gage_f = obs_f.loc[obs_f.obsnme.apply(lambda x: "gage" in x), :].copy()
    gage_f.loc[:, "time"] = gage_f.obsnme.apply(lambda x: float(x.split(':')[-1]))
    gage_c.sort_values(by="time",inplace=True)
    gage_f.sort_values(by="time", inplace=True)

    grp_c = set(hds_c.obgnme.unique())

    grp_f = set(hds_f.org_obgnme.unique())

    assert len(grp_f.symmetric_difference(grp_c)) == 0

    grp_c = hds_c.obgnme.unique()
    grp_c.sort()
    print(grp_c)
    print(label_dict)
    grp_c = [g for g in grp_c if g.replace("hds_usecol:","") in label_dict]
    print(grp_c)

    fig,axes = plt.subplots(len(grp_c)+1,1,figsize=(8,8))
    tags = ["trgw_2_2_9","trgw_2_33_7","trgw_0_9_1"]
    labels = ["gw_1","gw_2","gw_3"]
    for i,(tag,label,ax) in enumerate(zip(tags,labels,axes)):
    #for i,(grp,ax) in enumerate(zip(grp_c,axes)):
        grp = None
        for g in grp_c:
            if tag in g:
                grp = g
                break
        c = hds_c.loc[hds_c.obgnme==grp,:].copy()
        c.sort_values(by="time",inplace=True)
        f = hds_f.loc[hds_f.org_obgnme == grp,:].copy()
        f.sort_values(by="time",inplace=True)
        oe_c_g = oe_c.loc[:,c.obsnme].copy()
        oe_f_g = oe_f.loc[:, f.obsnme].copy()
        oe_c_g.values[oe_c_g.values < 30] = np.nan
        oe_f_g.values[oe_f_g.values < 30] = np.nan
        # lab = None
        # for l,t in label_dict.items():
        #     if l in grp:
        #         lab = t
        [ax.plot(c.time.values,oe_c_g.loc[i,:].values,color='b',alpha=0.7,lw=1.0,dashes=(2,2)) for i in oe_c_g.index]
        #[print(f.time.values, oe_f_g.loc[i, :].values) for i in oe_f_g.index]
        [ax.plot(f.time.values, oe_f_g.loc[i, :].values, color='g', alpha=0.5, lw=0.1) for i in oe_f_g.index]
        ax.set_ylabel("simulated groundwater level ($L$)")
        ax.set_xlabel("simulation time ($T$)")
        ax.set_title("{0}) {1}".format(abet[i],label),loc="left")
        #ax.set_ylim(34,40)
    [axes[-1].plot(gage_c.time.values,oe_c.loc[i,gage_c.obsnme].values,color='b',alpha=0.7,lw=1.0,dashes=(2,2)) for i in oe_c.index]
    [axes[-1].plot(gage_f.time.values, oe_f.loc[i, gage_f.obsnme].values, color='g', alpha=0.5, lw=0.1) for i in
     oe_f.index]
    axes[-1].set_ylabel("simulated surfacewaer flow ($\\frac{L^3}{T}$)")
    axes[-1].set_xlabel("simulation time ($T$)")
    axes[-1].set_title("D) sw_1", loc="left")
    plt.tight_layout()
    plt.savefig("obs_prior.pdf")
    plt.close(fig)


    fig,axes = plt.subplots(1,2,figsize=(8,4))
    forecasts = ["sfr_usecol:headwater_time:610.0","sfr_usecol:tailwater_time:610.0"]
    labels = ["A) headwater flux","B) tailwater_flux"]
    xmin = min(oe_c.loc[:,forecasts].min().min(),oe_f.loc[:,forecasts].min().min())
    xmax = max(oe_c.loc[:, forecasts].max().max(),oe_f.loc[:, forecasts].max().max())

    for forecast,ax,label in zip(forecasts,axes,labels):
        oe_c.loc[:,forecast].hist(ax=ax,bins=15,edgecolor="none",facecolor="b", alpha=0.5,label="lower resolution")
        oe_f.loc[:, forecast].hist(ax=ax, bins=15, edgecolor="none", facecolor="g", alpha=0.5, label="higher resolution")
        ax.set_yticks([])
        ax.set_xlabel("surface-water/groundwater flux ($\\frac{L}{T}$)")
        ax.set_title(label,loc="left")
        ax.set_xlim(xmin,xmax)
        ax.legend(loc="upper right")
        ax.grid(False)
    plt.tight_layout()
    plt.savefig("forecast_prior.pdf")
    plt.close(fig)

if __name__ == "__main__":

    # prep_mf6_model("temp_monthly")
    #setup_interface("temp_monthly_test",num_reals=100)
    #run_prior_mc("monthly_template")
    #
    #prep_mf6_model("temp_daily")
    #setup_interface("temp_daily_test",num_reals=100)
    #run_prior_mc("daily_template")

    make_kickass_figs()
